### ISSUE TITLE
How to have spouses without common children on the same level?

### ISSUE THREAD

**Issue by chaag6958** [BasicPrimitives/react#54]
Is there a way to mark items that have to be on the same level without having a common child?

**Comment by BasicPrimitives** [comment]
We eliminated this feature because it creates unnecessary complexity in the API. As soon as this feature is available the next question is how to add a label and marker for the spousal connection and set the order of spousal connections. So it is obvious from a basic use case, but the only solution for the following questions is to have explicit marriage nodes in the diagram.
